# program to demonstrate exceptional handing

try:
    #a = 10
    print(a)

except NameError as e:
    print(e)
